//! Blinc procedural macros
//!
//! Provides derive macros for the Blinc UI framework.
//!
//! # Platform-Agnostic Design
//!
//! The generated code uses traits from `blinc_core` and `blinc_animation`
//! rather than concrete types, enabling components to work across different
//! platforms without depending on `blinc_app`.
//!
//! # Scope and Instance Awareness
//!
//! The `BlincComponent` macro generates unique component keys that include
//! both scope information (module path + struct name) and support for
//! instance differentiation through key suffixes.
//!
//! ## Component Key Composition
//!
//! Keys are composed of three parts:
//! 1. **Scope key**: `module_path!()::StructName` - identifies the component type
//! 2. **Field key**: Field name for struct fields - identifies the field
//! 3. **Instance key**: User-provided or auto-generated suffix - differentiates instances
//!
//! ## Usage Patterns
//!
//! For single-instance components, use the field methods directly:
//! ```ignore
//! let scale = MyComponent::use_scale(ctx, 1.0, SpringConfig::snappy());
//! ```
//!
//! For multiple instances (e.g., in loops), use the `_for` variants with an instance key:
//! ```ignore
//! for i in 0..10 {
//!     let scale = MyComponent::use_scale_for(ctx, i, 1.0, SpringConfig::snappy());
//! }
//! ```
//!
//! For automatic instance keys based on call site (via `#[track_caller]`):
//! ```ignore
//! // Each call site gets a unique key automatically
//! let scale1 = MyComponent::use_scale_auto(ctx, 1.0, SpringConfig::snappy());
//! let scale2 = MyComponent::use_scale_auto(ctx, 1.0, SpringConfig::snappy()); // Different key!
//! ```

use proc_macro::TokenStream;
use quote::quote;
use syn::{parse_macro_input, Data, DeriveInput, Fields};

// =====================================================================
// #[extern_widget] — Rust → Blinc DSL widget export
// =====================================================================
//
// Generates the boilerplate that hand-rolling a DSL-exposed widget
// would need: an `extern "C"` JIT thunk decoding args + wrapping the
// builder fn's result in `WidgetBox::Custom`, plus a `register_<Name>`
// helper that calls into `BlincDsl::register_extern_widget` with the
// right `ExternWidgetSpec`. Re-exported from `blinc_dsl_core` so users
// only need one import.

/// Internal description of one user-fn parameter — what FFI shape it
/// crosses the JIT boundary as, how to decode it, and which DSL
/// `Type::Primitive` it maps to. Generated by `classify_param_type`
/// from a `syn::Type`.
struct ParamKind {
    /// The FFI param type that lands in the generated `extern "C" fn`
    /// signature (e.g., `*const i32` for `String`, the Rust primitive
    /// directly otherwise).
    ffi_ty: proc_macro2::TokenStream,
    /// Expression that decodes the FFI param into the user-fn's
    /// expected Rust type. `__arg` is the ident of the FFI arg in
    /// scope. For primitives that pass through unchanged, this is
    /// just `__arg`.
    decode: proc_macro2::TokenStream,
    /// The DSL `Type::Primitive(...)` variant that goes into
    /// `ExternWidgetSpec.param_types` and the matching `PropDef.ty`.
    type_expr: proc_macro2::TokenStream,
}

/// Map a parameter's `syn::Type` onto its [`ParamKind`]. Returns
/// `None` for any type the macro doesn't know how to marshal yet —
/// callers turn `None` into a `compile_error!` naming the offending
/// type so users get a clear message instead of mysterious codegen.
fn classify_param_type(ty: &syn::Type) -> Option<ParamKind> {
    let syn::Type::Path(p) = ty else {
        return None;
    };
    let ident = p.path.get_ident()?;
    match ident.to_string().as_str() {
        "String" => Some(ParamKind {
            ffi_ty: quote! { *const i32 },
            decode: quote! {
                // SAFETY: the registered signature has `String`
                // for this param, so the JIT guarantees a
                // length-prefixed UTF-8 buffer here.
                unsafe { ::blinc_dsl_core::__extern_widget_internals::decode_string(__arg) }
            },
            type_expr: quote! {
                ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::String
                )
            },
        }),
        "i32" => Some(ParamKind {
            ffi_ty: quote! { i32 },
            decode: quote! { __arg },
            type_expr: quote! {
                ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I32
                )
            },
        }),
        "i64" => Some(ParamKind {
            ffi_ty: quote! { i64 },
            decode: quote! { __arg },
            type_expr: quote! {
                ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
                )
            },
        }),
        "f64" => Some(ParamKind {
            ffi_ty: quote! { f64 },
            decode: quote! { __arg },
            type_expr: quote! {
                ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::F64
                )
            },
        }),
        _ => None,
    }
}

/// Parsed `#[extern_widget(...)]` attribute args. Today only `name =
/// "<DSL identifier>"` is supported; the field exists as its own
/// struct so adding future keys (e.g., `view_symbol = "..."`) is a
/// matter of extending the `Parse` impl.
struct ExternWidgetArgs {
    /// DSL-facing name.
    name: String,
    /// `styled` flag — when true, the macro wraps the widget in
    /// `Styled<W>` and the spec advertises a `__style` prop that
    /// the lowering pass populates from inline DSL styling args.
    styled: bool,
}

/// `#[children]` attribute on a struct field — marks the field as
/// the receiver for the parent's body block in DSL source. Field
/// type SHOULD be `Vec<Box<dyn ElementBuilder>>`; the macro
/// trusts the field type to be assignable from
/// `decode_children`'s return type, so a mismatch surfaces as a
/// regular type error inside the generated thunk.
fn field_has_children_attr(field: &syn::Field) -> bool {
    field
        .attrs
        .iter()
        .any(|attr| attr.path().is_ident("children"))
}

/// If the field carries `#[slot(name = "X")]`, return `"X"`.
fn field_slot_name(field: &syn::Field) -> Option<String> {
    let attr = field.attrs.iter().find(|a| a.path().is_ident("slot"))?;
    let mut name: Option<String> = None;
    let parse_result = attr.parse_nested_meta(|meta| {
        if meta.path.is_ident("name") {
            let lit: syn::LitStr = meta.value()?.parse()?;
            name = Some(lit.value());
            Ok(())
        } else {
            Err(meta.error("expected `name = \"...\"`"))
        }
    });
    let _ = parse_result;
    name
}

impl syn::parse::Parse for ExternWidgetArgs {
    fn parse(input: syn::parse::ParseStream) -> syn::Result<Self> {
        // Required: name = "<DslName>"
        let key: syn::Ident = input.parse()?;
        if key != "name" {
            return Err(syn::Error::new(
                key.span(),
                "expected `name = \"<DslName>\"`",
            ));
        }
        let _: syn::Token![=] = input.parse()?;
        let value: syn::LitStr = input.parse()?;

        // Optional comma-separated trailing flags (currently
        // just `styled`).
        let mut styled = false;
        while !input.is_empty() {
            let _: syn::Token![,] = input.parse()?;
            if input.is_empty() {
                break;
            }
            let flag: syn::Ident = input.parse()?;
            match flag.to_string().as_str() {
                "styled" => styled = true,
                other => {
                    return Err(syn::Error::new(
                        flag.span(),
                        format!("unknown #[extern_widget] flag `{other}` — expected `styled`"),
                    ));
                }
            }
        }
        Ok(Self {
            name: value.value(),
            styled,
        })
    }
}

/// Generate the JIT thunk + [`ExternWidget`] trait impl that
/// expose a Rust struct to Blinc DSL source.
///
/// **Widget shape** the macro accepts:
///
/// ```ignore
/// #[extern_widget(name = "FancyText")]
/// pub struct FancyText {
///     pub content: String,
/// }
///
/// impl ElementBuilder for FancyText { /* user UI logic */ }
/// ```
///
/// The struct's named fields become the DSL-visible props, in
/// declaration order. Each field type is independently marshalled
/// — see [`classify_param_type`] for the supported set
/// (`String`, `i32`, `i64`, `f64` today). Unsupported types
/// produce a `compile_error!` naming the offending field.
///
/// **Generated items:**
///
/// 1. The original struct — left intact (including any other
///    `#[derive(...)]` / impl blocks the user added).
/// 2. `extern "C" fn __blinc_extern_<Name>_view(args...) -> i64`
///    — JIT thunk that decodes FFI args, constructs
///    `Self { field1, field2, ... }`, and wraps the value in
///    `WidgetBox::Custom` via
///    [`into_handle`](::blinc_dsl_core::__extern_widget_internals::into_handle).
///    Requires `Self: ElementBuilder` (the user provides this
///    impl).
/// 3. `impl ExternWidget for <StructName>` — carries the
///    `DSL_NAME` constant and the `extern_widget_spec()` method
///    that points at the thunk above.
///
/// **Registration** flows through the trait: users call
///
/// ```ignore
/// dsl.register_extern_widget::<FancyText>()?;
/// ```
///
/// **JIT linker symbol** is always `$Blinc$<Name>$view` to match
/// the in-tree primitive convention (`$Blinc$Text$view`,
/// `$Blinc$Div$view`).
///
/// **Not yet supported:** tuple/unit structs, generic structs,
/// non-`pub` fields. The macro errors out on each.
#[proc_macro_attribute]
pub fn extern_widget(attr: TokenStream, item: TokenStream) -> TokenStream {
    let args = parse_macro_input!(attr as ExternWidgetArgs);
    let mut item_struct = parse_macro_input!(item as syn::ItemStruct);

    let struct_ident = item_struct.ident.clone();
    let dsl_name = args.name;
    let styled = args.styled;

    if !item_struct.generics.params.is_empty() {
        return syn::Error::new_spanned(
            &item_struct.generics,
            "#[extern_widget] doesn't support generic widgets yet — drop the type parameters \
             or hand-roll the registration via `BlincDsl::register_extern_widget_spec`",
        )
        .to_compile_error()
        .into();
    }

    // Pull the field list. Only named-field structs are
    // supported — tuple structs would lose prop names, unit
    // structs would mean a zero-prop widget which is rarely what
    // a user wants (and is trivially expressible by passing no
    // fields anyway, so the error pushes them toward the
    // explicit shape).
    let syn::Fields::Named(fields) = &item_struct.fields else {
        return syn::Error::new_spanned(
            &item_struct.fields,
            "#[extern_widget] requires a struct with named fields — tuple and unit structs aren't \
             supported",
        )
        .to_compile_error()
        .into();
    };

    // Compose generated symbol idents. Rust idents can't carry
    // `$`, so the thunk goes through a sanitised name (the
    // linker-visible symbol — `$Blinc$<Name>$view` — passes
    // through as a string in the `ExternWidgetSpec`).
    let thunk_ident = syn::Ident::new(
        &format!("__blinc_extern_{dsl_name}_view"),
        proc_macro2::Span::call_site(),
    );
    let view_symbol = format!("$Blinc${dsl_name}$view");

    // Partition fields: one optional #[children] field, any
    // number of #[slot(name = "X")] fields, the rest are scalar
    // props. FFI order: children → slots → scalars (matches the
    // substrate registry's slot-then-scalar prop ordering).
    let mut children_field: Option<&syn::Field> = None;
    let mut slot_fields: Vec<(&syn::Field, String)> = Vec::new();
    let mut scalar_fields: Vec<&syn::Field> = Vec::new();
    for field in &fields.named {
        if field_has_children_attr(field) {
            if children_field.is_some() {
                return syn::Error::new_spanned(
                    field,
                    "#[extern_widget] supports at most one `#[children]` field",
                )
                .to_compile_error()
                .into();
            }
            children_field = Some(field);
        } else if let Some(slot_name) = field_slot_name(field) {
            slot_fields.push((field, slot_name));
        } else {
            scalar_fields.push(field);
        }
    }

    let mut thunk_params: Vec<proc_macro2::TokenStream> = Vec::new();
    let mut thunk_decodes: Vec<proc_macro2::TokenStream> = Vec::new();
    let mut struct_inits: Vec<proc_macro2::TokenStream> = Vec::new();
    let mut prop_defs: Vec<proc_macro2::TokenStream> = Vec::new();
    let mut param_types: Vec<proc_macro2::TokenStream> = Vec::new();

    // Children field always at FFI position 0 — matches the
    // `lower_children_arrays_to_blocks` convention that inserts
    // the children-list pointer as the call's first positional
    // arg.
    if let Some(field) = children_field {
        if !matches!(field.vis, syn::Visibility::Public(_)) {
            return syn::Error::new_spanned(
                &field.vis,
                "#[extern_widget] `#[children]` field must be `pub`",
            )
            .to_compile_error()
            .into();
        }
        let field_ident = field
            .ident
            .as_ref()
            .expect("named fields always have idents");
        let ffi_arg_ident = syn::Ident::new("__arg_children", field_ident.span());
        thunk_params.push(quote! { #ffi_arg_ident: i64 });
        thunk_decodes.push(quote! {
            // SAFETY: `__arg_children` is the `i64`-encoded
            // payload of a `Box<Vec<WidgetHandle>>` minted by
            // `__new_child_list__`. The
            // `lower_children_arrays_to_blocks` pass is the
            // only producer of such pointers; the call site
            // can't forge one.
            let #field_ident = unsafe {
                ::blinc_dsl_core::__extern_widget_internals::decode_children(#ffi_arg_ident)
            };
        });
        struct_inits.push(quote! { #field_ident });
        // Substrate prop with a `children` name — that's what
        // `lower_children_arrays_to_blocks::callee_takes_children`
        // looks up in the registry to decide whether to splice
        // the list-pointer arg.
        prop_defs.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::PropDef {
                name: ::std::sync::Arc::from("children"),
                ty: ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
                ),
            }
        });
        param_types.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
            )
        });
    }

    // Slot fields, in declaration order. Each lands as a
    // separate `slot_<Name>: i64` FFI arg + matching PropDef.
    for (field, slot_name) in &slot_fields {
        if !matches!(field.vis, syn::Visibility::Public(_)) {
            return syn::Error::new_spanned(
                &field.vis,
                "#[extern_widget] `#[slot]` field must be `pub`",
            )
            .to_compile_error()
            .into();
        }
        let field_ident = field
            .ident
            .as_ref()
            .expect("named fields always have idents");
        let ffi_arg_ident = syn::Ident::new(&format!("__arg_slot_{slot_name}"), field_ident.span());
        let prop_name = format!("slot_{slot_name}");
        thunk_params.push(quote! { #ffi_arg_ident: i64 });
        thunk_decodes.push(quote! {
            // SAFETY: same contract as the default children
            // pointer — built by `__new_child_list__` /
            // `__push_child__` per the slot lowering pass.
            let #field_ident = unsafe {
                ::blinc_dsl_core::__extern_widget_internals::decode_children(#ffi_arg_ident)
            };
        });
        struct_inits.push(quote! { #field_ident });
        prop_defs.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::PropDef {
                name: ::std::sync::Arc::from(#prop_name),
                ty: ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
                ),
            }
        });
        param_types.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
            )
        });
    }

    // Scalar props, in declaration order.
    for (idx, field) in scalar_fields.iter().enumerate() {
        let field_ident = field
            .ident
            .as_ref()
            .expect("named fields always have idents");
        let field_name = field_ident.to_string();

        if !matches!(field.vis, syn::Visibility::Public(_)) {
            return syn::Error::new_spanned(
                &field.vis,
                "#[extern_widget] fields must be `pub` — non-public fields can't be set from DSL \
                 source. Make the field `pub` or move internal state into a wrapper struct.",
            )
            .to_compile_error()
            .into();
        }

        let Some(kind) = classify_param_type(&field.ty) else {
            return syn::Error::new_spanned(
                &field.ty,
                "#[extern_widget] scalar fields must be one of: String, i32, i64, f64 (or use \
                 `#[children]` for a `Vec<Box<dyn ElementBuilder>>` children slot)",
            )
            .to_compile_error()
            .into();
        };

        let ffi_arg_ident = syn::Ident::new(&format!("__arg_{idx}"), field_ident.span());
        let ffi_ty = &kind.ffi_ty;
        let decode = &kind.decode;
        let type_expr = &kind.type_expr;

        thunk_params.push(quote! { #ffi_arg_ident: #ffi_ty });
        thunk_decodes.push(quote! {
            let #field_ident = {
                let __arg = #ffi_arg_ident;
                #decode
            };
        });
        struct_inits.push(quote! { #field_ident });
        prop_defs.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::PropDef {
                name: ::std::sync::Arc::from(#field_name),
                ty: #type_expr,
            }
        });
        param_types.push(type_expr.clone());
    }

    // Styled flag: append `__style: i64` to the FFI signature
    // and prop list; the thunk decodes the overlay and wraps the
    // constructed widget in `Styled<W>`.
    if styled {
        thunk_params.push(quote! { __arg_style: i64 });
        prop_defs.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::PropDef {
                name: ::std::sync::Arc::from("__style"),
                ty: ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                    ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
                ),
            }
        });
        param_types.push(quote! {
            ::blinc_dsl_core::__extern_widget_internals::Type::Primitive(
                ::blinc_dsl_core::__extern_widget_internals::PrimitiveType::I64
            )
        });
    }

    // Strip macro-only field attributes before re-emitting the
    // struct.
    if let syn::Fields::Named(named) = &mut item_struct.fields {
        for field in &mut named.named {
            field
                .attrs
                .retain(|attr| !(attr.path().is_ident("children") || attr.path().is_ident("slot")));
        }
    }

    let widget_construction = if styled {
        quote! {
            // SAFETY: `__arg_style` is `0` or a
            // `__new_style_overlay__` pointer; either is safe to
            // pass to `decode_overlay`.
            let __overlay = unsafe {
                ::blinc_dsl_core::__extern_widget_internals::decode_overlay(__arg_style)
            };
            let __widget: Box<dyn ::blinc_layout::div::ElementBuilder> = Box::new(
                ::blinc_dsl_core::__extern_widget_internals::Styled::new(
                    #struct_ident { #(#struct_inits),* },
                    __overlay,
                )
            );
        }
    } else {
        quote! {
            let __widget: Box<dyn ::blinc_layout::div::ElementBuilder> =
                Box::new(#struct_ident { #(#struct_inits),* });
        }
    };

    let expanded = quote! {
        #item_struct

        #[doc(hidden)]
        #[allow(non_snake_case)]
        extern "C" fn #thunk_ident(#(#thunk_params),*) -> i64 {
            #(#thunk_decodes)*
            #widget_construction
            ::blinc_dsl_core::__extern_widget_internals::into_handle(__widget)
        }

        impl ::blinc_dsl_core::__extern_widget_internals::ExternWidget for #struct_ident {
            const DSL_NAME: &'static str = #dsl_name;

            fn extern_widget_spec()
                -> ::blinc_dsl_core::__extern_widget_internals::ExternWidgetSpec
            {
                use ::blinc_dsl_core::__extern_widget_internals::{
                    ExternWidgetSpec, PrimitiveType, Type,
                };
                ExternWidgetSpec {
                    name: #dsl_name.to_string(),
                    view_symbol: #view_symbol.to_string(),
                    props: vec![#(#prop_defs),*],
                    param_types: vec![#(#param_types),*],
                    return_type: Type::Primitive(PrimitiveType::I64),
                    extern_ptr: #thunk_ident as *const u8,
                }
            }
        }
    };

    TokenStream::from(expanded)
}

/// Check if a field has the `#[animation]` attribute
fn has_animation_attr(field: &syn::Field) -> bool {
    field
        .attrs
        .iter()
        .any(|attr| attr.path().is_ident("animation"))
}

/// Derive macro that generates a unique compile-time key for a component
/// and generates field accessors based on field attributes.
///
/// This enables type-safe access to animation and state hooks without manual string keys.
/// The key is generated from the full module path and struct name, ensuring
/// uniqueness across the codebase.
///
/// # Platform-Agnostic
///
/// The generated methods are generic over `BlincContext` and `AnimationContext` traits,
/// allowing components to work with any platform implementation (desktop, Android, web, etc.)
/// without depending on `blinc_app`.
///
/// # Scope and Instance Awareness
///
/// The macro generates both single-instance and keyed (`_for`) variants for each field:
/// - Single-instance: `use_<field>(ctx, ...)` - for components used once
/// - Keyed: `use_<field>_for(ctx, key, ...)` - for components used in loops/lists
///
/// # Field Attributes
///
/// - `#[animation]` - Field generates animation methods returning `SharedAnimatedValue`
/// - No attribute - Field generates state methods returning `State<FieldType>`
///
/// # Example - Unit Struct (simple component key)
///
/// ```ignore
/// use blinc_macros::BlincComponent;
///
/// #[derive(BlincComponent)]
/// pub struct AnimatedDemoCard;
///
/// // Works with any context implementing the required traits
/// fn build_ui<C: BlincContext + AnimationContext>(ctx: &C) -> impl ElementBuilder {
///     let ball_x = AnimatedDemoCard::use_animated_value(ctx, 20.0, SpringConfig::wobbly());
///     // ...
/// }
/// ```
///
/// # Example - Struct with Mixed Fields
///
/// ```ignore
/// use blinc_macros::BlincComponent;
///
/// #[derive(BlincComponent)]
/// pub struct PullToRefresh {
///     #[animation]
///     content_offset: f32,  // -> use_content_offset(ctx, initial, config)
///     #[animation]
///     icon_scale: f32,      // -> use_icon_scale(ctx, initial, config)
///     #[animation]
///     icon_opacity: f32,    // -> use_icon_opacity(ctx, initial, config)
/// }
///
/// fn build_ui<C: AnimationContext>(ctx: &C) -> impl ElementBuilder {
///     let offset = PullToRefresh::use_content_offset(ctx, 0.0, SpringConfig::wobbly());
///     let scale = PullToRefresh::use_icon_scale(ctx, 0.5, SpringConfig::snappy());
///     // ...
/// }
/// ```
///
/// # Example - Multiple Instances (Loop/List)
///
/// ```ignore
/// #[derive(BlincComponent)]
/// pub struct ListItem {
///     #[animation]
///     scale: f32,
///     selected: bool,
/// }
///
/// fn build_list<C: BlincContext + AnimationContext>(ctx: &C, items: &[Item]) -> impl ElementBuilder {
///     div().children(items.iter().enumerate().map(|(i, item)| {
///         // Use _for variants with instance key for uniqueness
///         let scale = ListItem::use_scale_for(ctx, i, 1.0, SpringConfig::snappy());
///         let selected = ListItem::use_selected_for(ctx, i, false);
///         // ...
///     }))
/// }
/// ```
///
/// # Example - State Values
///
/// ```ignore
/// #[derive(BlincComponent)]
/// pub struct Counter {
///     count: i32,           // -> use_count(ctx, initial) -> State<i32>
///     step: i32,            // -> use_step(ctx, initial) -> State<i32>
///     #[animation]
///     scale: f32,           // -> use_scale(ctx, initial, config) -> SharedAnimatedValue
/// }
/// ```
///
/// # Generated Code
///
/// For all structs, the macro generates:
/// - A `COMPONENT_KEY` constant containing the unique key
/// - `use_animated_value` / `use_animated_value_with` for ad-hoc spring animations
/// - `use_animated_timeline` / `use_animated_timeline_with` for timeline animations
///
/// For structs with named fields:
/// - Fields with `#[animation]`:
///   - `use_<field>(ctx, initial, config)` -> `SharedAnimatedValue`
///   - `use_<field>_for(ctx, key, initial, config)` -> `SharedAnimatedValue`
/// - Fields without attribute:
///   - `use_<field>(ctx, initial)` -> `State<FieldType>`
///   - `use_<field>_for(ctx, key, initial)` -> `State<FieldType>`
#[proc_macro_derive(BlincComponent, attributes(animation))]
pub fn derive_blinc_component(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    let name = &input.ident;

    // Extract named fields if present and generate appropriate methods
    let field_methods = match &input.data {
        Data::Struct(data) => match &data.fields {
            Fields::Named(fields) => {
                fields
                    .named
                    .iter()
                    .map(|field| {
                        let field_name = field.ident.as_ref().unwrap();
                        let field_type = &field.ty;
                        let method_name =
                            syn::Ident::new(&format!("use_{}", field_name), field_name.span());
                        let field_key = format!("{}", field_name);

                        // Generate _for method name for instance-aware variant
                        let method_name_for =
                            syn::Ident::new(&format!("use_{}_for", field_name), field_name.span());

                        // Generate _auto method name for caller-location-aware variant
                        let method_name_auto =
                            syn::Ident::new(&format!("use_{}_auto", field_name), field_name.span());

                        if has_animation_attr(field) {
                            // #[animation] attribute -> SharedAnimatedValue
                            quote! {
                                /// Get a persisted animated value for this field (single instance).
                                ///
                                /// Returns a `SharedAnimatedValue` that is persisted across UI rebuilds.
                                /// Use `use_<field>_for` when you need multiple instances.
                                pub fn #method_name<C: blinc_animation::AnimationContext>(
                                    ctx: &C,
                                    initial: f32,
                                    config: blinc_animation::SpringConfig,
                                ) -> blinc_animation::SharedAnimatedValue {
                                    let key = format!("{}:{}", Self::COMPONENT_KEY, #field_key);
                                    ctx.use_animated_value_for(key, initial, config)
                                }

                                /// Get a persisted animated value for this field with instance key.
                                ///
                                /// Use this when you have multiple instances of the same component
                                /// (e.g., in a loop or list). The `instance_key` differentiates
                                /// between instances.
                                ///
                                /// # Example
                                ///
                                /// ```ignore
                                /// for i in 0..10 {
                                ///     let scale = MyComponent::use_scale_for(ctx, i, 1.0, config);
                                /// }
                                /// ```
                                pub fn #method_name_for<C: blinc_animation::AnimationContext, K: std::fmt::Display>(
                                    ctx: &C,
                                    instance_key: K,
                                    initial: f32,
                                    config: blinc_animation::SpringConfig,
                                ) -> blinc_animation::SharedAnimatedValue {
                                    let key = format!("{}:{}:{}", Self::COMPONENT_KEY, #field_key, instance_key);
                                    ctx.use_animated_value_for(key, initial, config)
                                }

                                /// Get a persisted animated value with auto-generated instance key.
                                ///
                                /// Uses `#[track_caller]` to generate a unique key based on the
                                /// call site location. Each unique call site gets its own instance.
                                ///
                                /// Prefer `use_<field>_for` in loops where you control the key.
                                #[track_caller]
                                pub fn #method_name_auto<C: blinc_animation::AnimationContext>(
                                    ctx: &C,
                                    initial: f32,
                                    config: blinc_animation::SpringConfig,
                                ) -> blinc_animation::SharedAnimatedValue {
                                    let loc = std::panic::Location::caller();
                                    let key = format!("{}:{}:{}:{}:{}",
                                        Self::COMPONENT_KEY, #field_key,
                                        loc.file(), loc.line(), loc.column());
                                    ctx.use_animated_value_for(key, initial, config)
                                }
                            }
                        } else {
                            // No attribute -> State<T>
                            quote! {
                                /// Get a persisted state value for this field (single instance).
                                ///
                                /// Returns a `State<T>` that is persisted across UI rebuilds.
                                /// Use `use_<field>_for` when you need multiple instances.
                                pub fn #method_name<C: blinc_core::BlincContext>(
                                    ctx: &C,
                                    initial: #field_type,
                                ) -> blinc_core::State<#field_type>
                                where
                                    #field_type: Clone + Send + 'static,
                                {
                                    let key = format!("{}:{}", Self::COMPONENT_KEY, #field_key);
                                    ctx.use_state_keyed(&key, || initial)
                                }

                                /// Get a persisted state value for this field with instance key.
                                ///
                                /// Use this when you have multiple instances of the same component
                                /// (e.g., in a loop or list). The `instance_key` differentiates
                                /// between instances.
                                ///
                                /// # Example
                                ///
                                /// ```ignore
                                /// for i in 0..10 {
                                ///     let selected = MyComponent::use_selected_for(ctx, i, false);
                                /// }
                                /// ```
                                pub fn #method_name_for<C: blinc_core::BlincContext, K: std::fmt::Display>(
                                    ctx: &C,
                                    instance_key: K,
                                    initial: #field_type,
                                ) -> blinc_core::State<#field_type>
                                where
                                    #field_type: Clone + Send + 'static,
                                {
                                    let key = format!("{}:{}:{}", Self::COMPONENT_KEY, #field_key, instance_key);
                                    ctx.use_state_keyed(&key, || initial)
                                }

                                /// Get a persisted state value with auto-generated instance key.
                                ///
                                /// Uses `#[track_caller]` to generate a unique key based on the
                                /// call site location. Each unique call site gets its own instance.
                                ///
                                /// Prefer `use_<field>_for` in loops where you control the key.
                                #[track_caller]
                                pub fn #method_name_auto<C: blinc_core::BlincContext>(
                                    ctx: &C,
                                    initial: #field_type,
                                ) -> blinc_core::State<#field_type>
                                where
                                    #field_type: Clone + Send + 'static,
                                {
                                    let loc = std::panic::Location::caller();
                                    let key = format!("{}:{}:{}:{}:{}",
                                        Self::COMPONENT_KEY, #field_key,
                                        loc.file(), loc.line(), loc.column());
                                    ctx.use_state_keyed(&key, || initial)
                                }
                            }
                        }
                    })
                    .collect::<Vec<_>>()
            }
            Fields::Unnamed(_) => Vec::new(),
            Fields::Unit => Vec::new(),
        },
        _ => Vec::new(),
    };

    // We use module_path!() + stringify!() in the generated code for a unique key
    let expanded = quote! {
        impl #name {
            /// Unique compile-time key for this component type.
            ///
            /// This is the base key derived from the module path and struct name.
            /// For instance-specific keys, use `instance_key()` or `instance_key_for()`.
            pub const COMPONENT_KEY: &'static str = concat!(module_path!(), "::", stringify!(#name));

            /// Generate an instance key based on the call site location.
            ///
            /// Uses `#[track_caller]` to capture file:line:column, creating a unique
            /// key for each instantiation point. This is useful for `blinc_cn` components
            /// that need automatic instance differentiation.
            ///
            /// # Example
            ///
            /// ```ignore
            /// struct MyComponent;
            /// impl MyComponent {
            ///     fn new() -> Self {
            ///         let key = Self::instance_key(); // Unique per call site
            ///         // Use key with state/animation...
            ///         Self
            ///     }
            /// }
            /// ```
            #[track_caller]
            pub fn instance_key() -> String {
                let loc = std::panic::Location::caller();
                format!("{}:{}:{}:{}",
                    Self::COMPONENT_KEY,
                    loc.file(), loc.line(), loc.column())
            }

            /// Generate an instance key with a user-provided suffix.
            ///
            /// Use this in loops or when you need to combine automatic location-based
            /// keys with custom identifiers (like array indices).
            ///
            /// # Example
            ///
            /// ```ignore
            /// for i in 0..10 {
            ///     let key = ListItem::instance_key_for(i);
            ///     // Use key with state/animation...
            /// }
            /// ```
            #[track_caller]
            pub fn instance_key_for<K: std::fmt::Display>(suffix: K) -> String {
                let loc = std::panic::Location::caller();
                format!("{}:{}:{}:{}:{}",
                    Self::COMPONENT_KEY,
                    loc.file(), loc.line(), loc.column(),
                    suffix)
            }

            /// Get a persisted animated value for this component.
            ///
            /// The value is uniquely identified by the component type.
            /// Multiple calls with the same component return the same animation.
            /// Generic over any context implementing `AnimationContext`.
            pub fn use_animated_value<C: blinc_animation::AnimationContext>(
                ctx: &C,
                initial: f32,
                config: blinc_animation::SpringConfig,
            ) -> blinc_animation::SharedAnimatedValue {
                ctx.use_animated_value_for(Self::COMPONENT_KEY, initial, config)
            }

            /// Get a persisted animated value with a suffix for multiple values per component.
            ///
            /// Use this when a component needs multiple independent animated values.
            /// Generic over any context implementing `AnimationContext`.
            ///
            /// # Example
            ///
            /// ```ignore
            /// let x = MyComponent::use_animated_value_with(ctx, "x", 0.0, SpringConfig::default());
            /// let y = MyComponent::use_animated_value_with(ctx, "y", 0.0, SpringConfig::default());
            /// ```
            pub fn use_animated_value_with<C: blinc_animation::AnimationContext>(
                ctx: &C,
                suffix: &str,
                initial: f32,
                config: blinc_animation::SpringConfig,
            ) -> blinc_animation::SharedAnimatedValue {
                let key = format!("{}:{}", Self::COMPONENT_KEY, suffix);
                ctx.use_animated_value_for(key, initial, config)
            }

            /// Get a persisted animated timeline for this component.
            ///
            /// The timeline is uniquely identified by the component type.
            /// Multiple calls with the same component return the same timeline.
            /// Generic over any context implementing `AnimationContext`.
            pub fn use_animated_timeline<C: blinc_animation::AnimationContext>(
                ctx: &C,
            ) -> blinc_animation::SharedAnimatedTimeline {
                ctx.use_animated_timeline_for(Self::COMPONENT_KEY)
            }

            /// Get a persisted animated timeline with a suffix for multiple timelines per component.
            ///
            /// Use this when a component needs multiple independent timelines.
            /// Generic over any context implementing `AnimationContext`.
            pub fn use_animated_timeline_with<C: blinc_animation::AnimationContext>(
                ctx: &C,
                suffix: &str,
            ) -> blinc_animation::SharedAnimatedTimeline {
                let key = format!("{}:{}", Self::COMPONENT_KEY, suffix);
                ctx.use_animated_timeline_for(key)
            }

            #(#field_methods)*
        }
    };

    TokenStream::from(expanded)
}
