//! Blinc runtime substrate.
//!
//! Runtime-agnostic plumbing shared by the JIT path (the
//! `blinc_dsl_core` crate, which compiles `.blinc` source through
//! Zyntax+Cranelift in-process) and the AOT path (a future
//! per-app crate generated by Zyntax+LLVM at build time). Both
//! produce the same surface: a set of callable symbols + a pure-
//! data FSM registry. This crate is what consumes that surface
//! and bridges it to widget-side machinery (`Stateful<S>`).
//!
//! The headline module is [`fsm`] — see its docs for the
//! architecture diagram.

pub mod component;
pub mod fsm;
pub mod reactive_value;
pub mod reload;
pub mod signal;
pub mod view;

/// Test-only mutex that serializes every test touching the
/// process-wide registries (signal table, fsm registry, component
/// registry, guard dispatcher). Without it, `signal::tests::*`,
/// `reload::tests::*`, and any other test that calls
/// `signal::clear_all` / `clear_all_destructive` race each other
/// under parallel `cargo test` and intermittently observe a
/// just-planted signal as `None` because a sibling test wiped it
/// between the `set` and the `assert_eq!`. Surfaces most often
/// under `cargo llvm-cov` instrumentation where slowdowns shift
/// test interleaving. Acquire at the top of every test that
/// mutates one of those globals.
#[cfg(test)]
pub(crate) static GLOBAL_REGISTRY_TEST_LOCK: std::sync::Mutex<()> = std::sync::Mutex::new(());

// Convenience re-exports — `Reactive<T>` is the first DSL value
// type and lives at the top of every consumer's import list.
pub use reactive_value::{
    REACTIVE_TAG_COMPUTED, REACTIVE_TAG_LITERAL, REACTIVE_TAG_SIGNAL, Reactive,
};

// `ZyntaxValue` is the canonical runtime value representation
// — JIT and AOT compiled code from Zyntax both produce it.
// Re-exported here so the substrate's surface includes the
// value enum without callers needing to depend on
// `zyntax_embed` themselves.
pub use zyntax_embed::ZyntaxValue;

pub use blinc_layout;

pub use blinc_core;

#[cfg(feature = "blinc_animation")]
pub use blinc_animation;

#[cfg(feature = "blinc_gpu")]
pub use blinc_gpu;

#[cfg(feature = "blinc_paint")]
pub use blinc_paint;

// #[cfg(feature = "blinc_cn")]
// pub use blinc_cn;

/// Initialize the Blinc runtime
pub fn init() -> anyhow::Result<()> {
    Ok(())
}
